add: prettier format script

diff --git a/.github/workflows/prettier-formatting-check.yml b/.github/workflows/prettier-formatting-check.yml
--- a/.github/workflows/prettier-formatting-check.yml
+++ b/.github/workflows/prettier-formatting-check.yml
@@ -23,5 +23,6 @@ jobs:
         run: npm install
 
       - name: Run Prettier check
-        run: npx prettier --check "**/*.{js,ts,tsx,jsx,json,css}"
+        run: |
+          npx prettier --check "**/*.{js,ts,tsx,jsx,json,css}" || (echo "Prettier check failed. Please run 'npm run prettier:format' locally to fix the formatting issues and push the changes." && exit 1)
 
